import { Idata } from "../module/module";

export const products: Array<Idata> = [
    {
        id: 1,
        name: 'iPhone 13',
        brand: 'Apple',
        price: 999,
        image: 'https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/0/8/4/-original-imagfhu75eupxyft.jpeg?q=70',
        isAvailable: true,
    },
    {
        id: 2,
        name: 'Samsung Galaxy S21',
        brand: 'Samsung',
        price: 899,
        image: 'https://rukminim2.flixcart.com/image/312/312/ktketu80/mobile/6/n/d/iphone-13-mlpg3hn-a-apple-original-imag6vpyghayhhrh.jpeg?q=70',
        isAvailable: false,
    },
    {
        id: 3,
        name: 'Google Pixel 6',
        brand: 'Google',
        price: 799,
        image: 'https://rukminim2.flixcart.com/image/312/312/ktketu80/mobile/8/z/w/iphone-13-mlph3hn-a-apple-original-imag6vzzhrxgazsg.jpeg?q=70',
        isAvailable: true,
    },
    {
        id: 4,
        name: 'OnePlus 9 Pro',
        brand: 'OnePlus',
        price: 899,
        image:'' ,
        isAvailable: true,
    },
    {
        id: 5,
        name: 'Xiaomi Mi 11',
        brand: 'Xiaomi',
        price: 699,
        image: 'https://rukminim2.flixcart.com/image/312/312/mobile/x/2/k/blackberry-curve-3g-9300-original-imad5h6b4fkfhbdf.jpeg?q=70',
        isAvailable: true,
    },
    {
        id: 6,
        name: 'Sony Xperia 1 III',
        brand: 'Sony',
        price: 1199,
        image: 'https://rukminim2.flixcart.com/image/312/312/jj4ln680/mobile/y/d/w/asus-zenfone-5z-zs621kl-2a001in-zs621kl-2a011in-original-imaf6rn7eyfngknj.jpeg?q=70',
        isAvailable: true,
    },
    {
        id: 7,
        name: 'LG Velvet',
        brand: 'LG',
        price: 599,
        image: 'https://rukminim2.flixcart.com/image/312/312/k2jbyq80pkrrdj/mobile-refurbished/x/y/b/p30-lite-128-c-marie-l22a-huawei-4-original-imafghwdpthze4pb.jpeg?q=70',
        isAvailable: false,
    },
    {
        id: 8,
        name: 'Huawei P40 Pro',
        brand: 'Huawei',
        price: 899,
        image: 'https://rukminim2.flixcart.com/image/312/312/ktketu80/mobile/s/l/c/iphone-13-mlpf3hn-a-apple-original-imag6vzz5qvejz8z.jpeg?q=70',
        isAvailable: true,
    },
    {
        id: 9,
        name: 'Motorola Moto G Power',
        brand: 'Motorola',
        price: 249,
        image: 'https://rukminim2.flixcart.com/image/312/312/kzd147k0/mobile/o/v/y/-original-imagbe7wpagygwtf.jpeg?q=70',
        isAvailable: true,
    },
    {
        id: 10,
        name: 'Nokia 8.3',
        brand: 'Nokia',
        price: 499,
        image: 'https://rukminim2.flixcart.com/image/312/312/k2jbyq80pkrrdj/mobile-refurbished/x/y/b/p30-lite-128-c-marie-l22a-huawei-4-original-imafghwdpthze4pb.jpeg?q=70',
        isAvailable: true,
    }
];